FROM jenkinsci/jnlp-slave

## Create Letsencrypt based certificate and them manipulation for jenkns slave here https://github.com/hughperkins/howto-jenkins-ssl/blob/master/letsencrypt.md
COPY cacerts $JAVA_HOME/jre/lib/security/cacerts 